remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Minimal JS Image Classifiers
description: Some basic examples of client interfaces to a computer vision API

author:
  name: CinnamonRoll
